stages:
  - build
  - check_ports
  - deploy

build:
  stage: build
  script:
    - echo "Build stage" # Здесь можно добавить команды сборки проекта
  artifacts:
    paths:
      - public/ # Убедись, что директория совпадает с Firebase

check_ports:
  stage: check_ports
  script:
    # Проверка прослушиваемых портов с использованием 'ss' (более современный инструмент чем netstat)
    - echo "Checking open ports..."
    - ss -tuln
    # Альтернатива с netstat (если ss недоступен):
    # - netstat -tuln
  only:
    - main

deploy:
  stage: deploy
  script:
    - npm install -g firebase-tools
    - firebase deploy --token "$FIREBASE_TOKEN" --only hosting
  only:
    - main